### ISSUE TITLE
There are errors when I try to write values ​​for excel : AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by vanhai493** [bartkl/robotframework-excellentlibrary#14]
There are errors when I try to write values ​​for excel.
Please view my code
*** Settings ***
Library           ExcellentLibrary
Library           SeleniumLibrary

*** Test Cases ***
login
    go to v
    read data

*** Keywords ***
go to v
    Open browser    http:xxx    chrome
    Maximize Browser Window

read data
    Open Workbook    C:/Users/Admin/Desktop/demo/resource/data.xlsx
    Switch Sheet    Login
    @{data}=    Read Sheet Data    get_column_names_from_header_row=False
    : FOR    ${int}    IN    @{data}
    \    ${kq}=    Run Keyword And Return Status    hai1    ${int['name']}    ${int['pass']}    ${int['error message']}
    \    Run Keyword If    "${kq}"=="True"    Write To Cell    ${int['status']}    "ok"
    \    ...    ELSE    Write To Cell    ${int['status']}    "FAIL"
    \    Save
    Close Workbook

result
    ${kq}=    Run Keyword And Return    read data
    Write To Cell    ${int['status']}    ${kq}

hai1
    [Arguments]    ${name}    ${pass}    ${err}
    Clear Element Text    id=username
    input text    id=username    `${name}`
    Clear Element Text    id=password
    input text    id=password    ${pass}
    click button    id=hongntk
    page should contain    ${err}

and this link image FAIL [http://prntscr.com/kx3b1c](url)
and check excel file [http://prntscr.com/kx3bni](url)

**Comment by bartkl** [comment]
When you use `Read Sheet Data`, it stores all the data in a list of dictionaries or lists, depending on the column parameters. So, when you loop though this list (as you do with `@{data}`), it's going to be an ordinary structure of values, without any connection to the sheet/sheet or cell object. So when you pass `${int[status]}` as a locator for the cell to write to, you pass in `None` (since the cell value is empty). And of course, a `None` value won't tell `Write To Cell` much about what cell to write to :). I recommend reading the [keyword documentation](https://bartkl.github.io/ExcellentLibrary/v0.9.2.html#Write%20To%20Cell) for more details on how to identify cells.

Also, you seemed to expect being able to identify by column name to write. This library does not currently truly support columns, despite the fact that it may be suggested by the workings of `Read Sheet Data`. Maybe you want to join this discussion which seems related: #9 

Okay, so let's move on to how you can achieve your goal.
If I understand your goal correctly, you want to write the status of the login attempt to the appropriate column _status_.

What you might want to try:
```robot
# [...]
:FOR  ${i}  ${int}  IN ENUMERATE  @{data}
\  ${kq}= Run Keyword And Return Status  hai1  ${int['name']}  ${int['pass']}  ${int['error message']}
\  Run Keyword If "${kq}"=="True" Write To Cell  ${i}, 4 "ok"
\  ... ELSE Write To Cell ${int['status']} "FAIL"
\  Save
# [...]
```
If you're not familiar with the for-in-enumerate loop, read about it in the [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id579).
The `4` is the hardcoded column number of the _status_ column. You could make a mapping between the column names and their numbers, that's all up to you.

On another note: what surprises me is that you pass in `get_column_names_from_header_row=False`, but your log shows that the rows are stored to dictionaries nonetheless. That seems like a bug. I'll have to look into that.

**Comment by vanhai493** [comment]
thank mate!
