### ISSUE TITLE
IllegalCharacterError when there's control characters in data

### ISSUE THREAD

**Issue by MichielYKamp** [bartkl/robotframework-excellentlibrary#15]
Wanneer het control character \x1b in een string voorkomt, dan gaat het keywoord "write to cell" fout met en "IllegalCharacterError" exception uit de openpyxl library.

Workaround is nu om dit karakter uit de string te halen voor aanroep van dit keywoord, maar liever zou ik dit (samen met eventueel andere ongewenste karakters) in de library hebben.

Run deze test case om te reproduceren:

`*** Settings ***
Library  ExcellentLibrary

*** Test Cases ***
Test title
    open workbook  test.xlsx
    switch sheet  Blad1
    ${line}  set variable  ccuA \x1b2[5hav?%http dbg=0 modified=1
    write to cell  A1  ${line}
    save`

**Comment by bartkl** [comment]
Hello Michiel,

Personally I feel like it's the user's own responsibility what data is read/written to from/to cells. Removing non-printable (control) characters from a string is very straightforward string manipulation that I believe every user ought to know about. One could consider creating a utility keyword for this, but I don't see why this is supposed to be part of this library.

If you still feel it belongs here let me know. Otherwise please close the issue.

Bart
