### ISSUE TITLE
don't read header of excel

### ISSUE THREAD

**Issue by hainvd2t** [bartkl/robotframework-excellentlibrary#19]
hi!
I've using keyword Read Sheet Data , I want do not read header of excel, I see in docs get_column_names_from_header_row=False, I think it no read header but not :(
please help me!
http://prntscr.com/n0fltk

**Comment by bartkl** [comment]
Hello,

What I understand you want to do is to read the sheet data as a list of lists, without column names. Skipping the header row in that scenario is currently not immediately supported. You'll need to work around it:

```robot
@{all}=  Read Sheet Data
@{data}=  Get Slice From List  ${all}  1
```

Make sure you import the `Collections` library in order to use the `Get Slice From List` keyword.

Thanks for pointing this use case out. In the future I might need to reconsider the logic behind the parameters and perhaps rewrite it to support this. It's low priority though, since this workaround is very readable and straightforward.

**Comment by hainvd2t** [comment]
ok man! 
thank so much!
